import { TaskHistory } from './types';

export const taskHistory: TaskHistory[] = [
  {
    id: "hist-01",
    taskId: "task-01",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-05",
    changedAt: "2023-03-05T09:00:00Z",
  },
  {
    id: "hist-02",
    taskId: "task-01",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "COMPLETED",
    changedBy: "user-05",
    changedAt: "2023-03-14T16:30:00Z",
  },
  {
    id: "hist-03",
    taskId: "task-02",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-02",
    changedAt: "2023-03-16T09:00:00Z",
  },
  {
    id: "hist-04",
    taskId: "task-02",
    fieldChanged: "description",
    oldValue: "Develop React components for the new dashboard design",
    newValue:
      "Develop React components for the new dashboard design, including activity feed, metrics cards, and navigation",
    changedBy: "user-09",
    changedAt: "2023-03-18T11:30:00Z",
  },
  {
    id: "hist-05",
    taskId: "task-02",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "COMPLETED",
    changedBy: "user-02",
    changedAt: "2023-03-29T15:45:00Z",
  },
  {
    id: "hist-06",
    taskId: "task-03",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-03",
    changedAt: "2023-03-16T09:00:00Z",
  },
  {
    id: "hist-07",
    taskId: "task-03",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "COMPLETED",
    changedBy: "user-03",
    changedAt: "2023-03-27T14:30:00Z",
  },
  {
    id: "hist-08",
    taskId: "task-06",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-06",
    changedAt: "2023-04-17T09:00:00Z",
  },
  {
    id: "hist-09",
    taskId: "task-06",
    fieldChanged: "priority",
    oldValue: "LOW",
    newValue: "MEDIUM",
    changedBy: "user-09",
    changedAt: "2023-04-18T14:30:00Z",
  },
  {
    id: "hist-10",
    taskId: "task-07",
    fieldChanged: "assigneeId",
    oldValue: null,
    newValue: "user-02",
    changedBy: "user-01",
    changedAt: "2023-04-20T09:30:00Z",
  },
  {
    id: "hist-11",
    taskId: "task-08",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-12",
    changedAt: "2023-03-15T09:00:00Z",
  },
  {
    id: "hist-12",
    taskId: "task-08",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "COMPLETED",
    changedBy: "user-12",
    changedAt: "2023-03-30T16:00:00Z",
  },
  {
    id: "hist-13",
    taskId: "task-09",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-03",
    changedAt: "2023-04-03T09:00:00Z",
  },
  {
    id: "hist-14",
    taskId: "task-09",
    fieldChanged: "storyPoints",
    oldValue: "8",
    newValue: "13",
    changedBy: "user-12",
    changedAt: "2023-04-05T13:45:00Z",
  },
  {
    id: "hist-15",
    taskId: "task-10",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-08",
    changedAt: "2023-04-10T09:00:00Z",
  },
  {
    id: "hist-16",
    taskId: "task-17",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-03",
    changedAt: "2023-04-20T09:00:00Z",
  },
  {
    id: "hist-17",
    taskId: "task-17",
    fieldChanged: "priority",
    oldValue: "HIGH",
    newValue: "HIGHEST",
    changedBy: "user-10",
    changedAt: "2023-04-20T10:15:00Z",
  },
  {
    id: "hist-18",
    taskId: "task-21",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-03",
    changedAt: "2023-04-10T09:00:00Z",
  },
  {
    id: "hist-19",
    taskId: "task-21",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "IN_REVIEW",
    changedBy: "user-03",
    changedAt: "2023-04-26T15:45:00Z",
  },
  {
    id: "hist-20",
    taskId: "task-22",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-02",
    changedAt: "2023-04-15T09:00:00Z",
  },
  {
    id: "hist-21",
    taskId: "task-22",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "IN_REVIEW",
    changedBy: "user-02",
    changedAt: "2023-04-24T16:30:00Z",
  },
  {
    id: "hist-22",
    taskId: "task-27",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-16",
    changedAt: "2023-03-20T09:00:00Z",
  },
  {
    id: "hist-23",
    taskId: "task-27",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "COMPLETED",
    changedBy: "user-16",
    changedAt: "2023-04-06T16:30:00Z",
  },
  {
    id: "hist-24",
    taskId: "task-28",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-12",
    changedAt: "2023-04-10T09:00:00Z",
  },
  {
    id: "hist-25",
    taskId: "task-29",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-14",
    changedAt: "2023-04-17T09:00:00Z",
  },
  {
    id: "hist-26",
    taskId: "task-29",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "BLOCKED",
    changedBy: "user-14",
    changedAt: "2023-04-26T14:30:00Z",
  },
  {
    id: "hist-27",
    taskId: "task-30",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-14",
    changedAt: "2023-04-10T09:00:00Z",
  },
  {
    id: "hist-28",
    taskId: "task-30",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "COMPLETED",
    changedBy: "user-14",
    changedAt: "2023-04-27T15:45:00Z",
  },
  {
    id: "hist-29",
    taskId: "task-31",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-14",
    changedAt: "2023-05-01T09:00:00Z",
  },
  {
    id: "hist-30",
    taskId: "task-32",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-03",
    changedAt: "2023-05-01T09:00:00Z",
  },
  {
    id: "hist-31",
    taskId: "task-35",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-12",
    changedAt: "2023-02-05T09:00:00Z",
  },
  {
    id: "hist-32",
    taskId: "task-35",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "COMPLETED",
    changedBy: "user-12",
    changedAt: "2023-02-23T16:30:00Z",
  },
  {
    id: "hist-33",
    taskId: "task-36",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-14",
    changedAt: "2023-02-27T09:00:00Z",
  },
  {
    id: "hist-34",
    taskId: "task-36",
    fieldChanged: "status",
    oldValue: "IN_PROGRESS",
    newValue: "COMPLETED",
    changedBy: "user-14",
    changedAt: "2023-03-16T15:45:00Z",
  },
  {
    id: "hist-35",
    taskId: "task-16",
    fieldChanged: "status",
    oldValue: "TODO",
    newValue: "IN_PROGRESS",
    changedBy: "user-02",
    changedAt: "2023-04-03T09:00:00Z",
  },
];